site_name: MaadiX Documetnación
site_description: Tutoriales y Gúias 
pages:
    - Home: index.md
    - Usuarios: users.md
    - Dominios: dominios.md
    - Email: email.md
    - VPN: vpn.md
    - Mysql: mysql.md
    - Etherpad: etherpad.md
    - Crear&nbsp;Web: create-web.md
theme: readthedocs
